language: python

python:
      - "3.4"
      - "3.5"
      - "3.6"
      - "3.7"
      - "3.8"

before_install:
    - "pip install -U pip"
install:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then pip install -U --upgrade-strategy eager --prefer-binary --editable .[dev]; fi
    - if [[ $TRAVIS_PYTHON_VERSION != 3.4 ]]; then pip install -U --upgrade-strategy eager --prefer-binary --editable .[dev,fast]; fi
script:
    - "pytest -v  --cov-report= --cov=orbit_predictor tests/"
after_script:
    - "flake8 orbit_predictor"

# report coverage to coveralls.io
after_success:
    - "pip install coveralls"
    - coveralls

cache:
  apt: true
  pip: true
